name: 'Checkmarx CxFlow Action'
description: 'Simplify Checkmarx Scanning of source code along with Result consumption leveraging Checkmarx CxFlow solution.'
author: 'Checkmarx Technical Services'
inputs:
  checkmarx_url:
    required: true
    description: 'Provide Checkmarx URL'
    default: ''
  team:
    required: true
    description: 'Select a Checkmarx Team'
    default: '/CxServer/SP/Company'
  checkmarx_username:
    required: true
    description: 'Provide Checkmarx Username'
    default: ''
  checkmarx_password:
    required: true
    description: 'Provide Checkmarx Password'
    default: ''
  checkmarx_client_secret:
    required: true
    description: 'Provide Checkmarx Client Secret'
    default: ''
  project:
    required: true
    default: ''
    description: 'Select a Checkmarx Project'
  app:
    required: false
    default: 'SampleApp'
    description: 'Select an Application Name used by downstream bug tracker systems'  
  preset:
    required: false
    default: 'High and Medium'
    description: 'Select a Checkmarx Preset'
  break_build:
    required: false
    default: false
    description: 'Break build based on Checkmarx findings?'
  bug_tracker:
    required: false
    default: Sarif
    description: 'Bug tracker for the scan results.'
  incremental:
    required: false
    default: true
    description: 'Incremental Scans?'
  params:
    required: false
    default: ''
    description: 'Additional CLI parameters'
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub API Token'
  scanners:
    required: true
    default: ''
    description: 'Vulnerability Scanners (sast, sca, cxgo)'
  extra_certificates:
    required: false
    default: ''
    description: 'Subdirectory containing extra X509 certificate files (.crt) to be imported into the CxFlow JRE. Example: \"certificates\"'
  cxflow_version:
    description: 'Version of CxFlow to use'
    required: false
    default: '198173'  
######### SCA Properties ##########
  sca_api_url:
    required: false
    description: 'Provide SCA API URL'
    default: 'https://api.scacheckmarx.com'
  sca_app_url:
    required: false
    description: 'Provide SCA APP URL'
    default: 'https://sca.scacheckmarx.com'
  sca_access_control_url:
    required: false
    description: 'Provide SCA Access Control URL'
    default: 'https://platform.checkmarx.net'
  sca_tenant:
    required: false
    description: 'Provide SCA Tenant'
    default: ''
  sca_username:
    required: false
    description: 'Provide SCA Username'
    default: ''
  sca_password:
    required: false
    description: 'Provide SCA Password'
    default: ''
  ######### CxGo Properties ##########
  cxgo_client_secret:
    required: false
    description: 'Provide CxGo Client Secret'
    default: ''
  cxgo_base_url:
    required: false
    description: 'Provide CxGo API URL'
    default: 'https://api.checkmarx.net'
  cxgo_portal_url:
    required: false
    description: 'Provide CxGo Portal URL'
    default: 'https://cloud.checkmarx.net'
  ######### Java/JVM Properties ##########
  java_opts: 
    required: false
    description: Java options will be passed to java
    default: -XX:MaxRAMPercentage=75.0
  ######### Jira Properties ##########
  jira_url:
    required: false
    description: 'Jira URL'
    default: ''
  jira_username:
    required: false
    description: 'Jira Username'
    default: ''
  jira_token:
    required: false
    description: 'Jira Token'
    default: ''
  jira_project:
    required: false
    description: 'Jira Project'
    default: ''
  jira_issue_type:
    required: false
    description: 'Jira Issue Type'
    default: ''
  jira_open_transition:
    required: false
    description: 'Jira Open Transition'
    default: ''
  jira_close_transition:
    required: false
    description: 'Jira Close Transition'
    default: ''
  jira_open_status:
    required: false
    description: 'Jira Open Status'
    default: ''
  jira_closed_status:
    required: false
    description: 'Jira Closed Status'
    default: ''

using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
      repository: itsKedar/checkmarx-cxflow-github-action
	  
    - name: Build Docker image
      run: docker build --build-arg CXFLOW_VERSION=${{ inputs.cxflow_version }} -t my-cxflow-app .
      shell: bash
      
    - name: Run Docker container
      run: |
        docker run -e TEAM=${{ inputs.team }} \
                   -e PROJECT=${{ inputs.project }} \
                   -e APP=${{ inputs.app }} \
                   -e CHECKMARX_USERNAME=${{ inputs.checkmarx_username }} \
                   -e CHECKMARX_PASSWORD=${{ inputs.checkmarx_password }} \
                   -e CHECKMARX_CLIENT_SECRET=${{ inputs.checkmarx_client_secret }} \
                   -e CHECKMARX_URL=${{ inputs.checkmarx_url }} \
                   -e PRESET=${{ inputs.preset }} \
                   -e INCREMENTAL=${{ inputs.incremental }} \
                   -e BREAK_BUILD=${{ inputs.break_build }} \
                   -e PARAMS=${{ inputs.params }} \
                   -e GITHUB_TOKEN=${{ inputs.github_token }} \
                   -e SCANNERS=${{ inputs.scanners }} \
                   -e SCA_API_URL=${{ inputs.sca_api_url }} \
                   -e SCA_APP_URL=${{ inputs.sca_app_url }} \
                   -e SCA_ACCESS_CONTROL_URL=${{ inputs.sca_access_control_url }} \
                   -e SCA_TENANT=${{ inputs.sca_tenant }} \
                   -e SCA_USERNAME=${{ inputs.sca_username }} \
                   -e SCA_PASSWORD=${{ inputs.sca_password }} \
                   -e CXGO_CLIENT_SECRET=${{ inputs.cxgo_client_secret }} \
                   -e CXGO_BASE_URL=${{ inputs.cxgo_base_url }} \
                   -e CXGO_PORTAL_URL=${{ inputs.cxgo_portal_url }} \
                   -e JAVA_OPTS=${{ inputs.java_opts }} \
                   -e JIRA_URL=${{ inputs.jira_url }} \
                   -e JIRA_USERNAME=${{ inputs.jira_username }} \
                   -e JIRA_TOKEN=${{ inputs.jira_token }} \
                   -e JIRA_PROJECT=${{ inputs.jira_project }} \
                   -e JIRA_ISSUE_TYPE=${{ inputs.jira_issue_type }} \
                   -e JIRA_OPEN_TRANSITION=${{ inputs.jira_open_transition }} \
                   -e JIRA_CLOSE_TRANSITION=${{ inputs.jira_close_transition }} \
                   -e JIRA_CLOSED_STATUS=${{ inputs.jira_closed_status }} \
                   my-cxflow-app
      shell: bash        
branding:
  icon: 'check'
  color: 'green'
