name: Checkmarx SCA Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: <ProjectName>
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: <SCATenant>
        sca_username: ${{ secrets.CX_SCA_USERNAME }} #To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CX_SCA_PASSWORD }} #To be stored in GitHub Secrets.
        break_build: false
        scanners: sca
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }}  --branch=${{ github.ref	}}  --repo-url="<GitHubRepoUrl>"

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

