name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1 #Github Action version
      with:
        project: <ProjectName>
        ast_api_url: <url-for-ast>
        ast_webapp_url: <url-for-ast>
        ast_client_id: CxFlow #client-id confgiured within AST portal.
        ast_client_secret: ${{ secrets.AST_CLIENT_SECRET }} #To be stored in GitHub Secrets.
        break_build: false
        scanners: ast
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }}  --branch=${{ github.ref }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: cx.sarif

